### ISSUE TITLE
Add some bundled gnome apps

### ISSUE THREAD

**Issue by AndriyanaNS1225** [flipflop97/Mato#14]
add some bundled apps from gnome, like
- [x] `totem` (Videos)
- [x] `file-roller` (Archive Manager)
- [x] `gnome-calculator` (Calculator)
- [x] `gnome-screenshot` (Screenshot)
- [x] `gnome-font-viewer` (Font Viewer)
- [x] `epiphany` (Web)
- [x] and `rhythmbox` please, if you don't mind :+1:

**Comment by flipflop97** [comment]
With [Web](https://flipflop97.github.io/Mato/#applications/org.gnome.Epiphany) added this issue is now closed.
