### ISSUE TITLE
Icons and context menu problem

### ISSUE THREAD

**Issue by elib0** [flipflop97/Mato#19]
After installing my desktop icons and context menu disappear (right click) linux mint 18.1 x64

Thanks for help

**Comment by flipflop97** [comment]
I can't really imagine how an icon pack would break these things other than a bug in your desktop environment. Can you provide some more information like desktop environment + version and how to reproduce the issue (which context menus are affected).

**Comment by flipflop97** [comment]
Closed due to inactivity
