### ISSUE TITLE
Add all icons on Ubuntu && VScode

### ISSUE THREAD

**Issue by joaoeudes7** [flipflop97/Mato#26]
Add icons please! ^^ Is perfect!

**Comment by flipflop97** [comment]
Hi @joaoeudes7 ,
I already added the Visual Studio code icon to the icon pack, if it isn't showing up for you on the latest version can you run the following command in your terminal and paste the output here? This will allow me to fix it.
```bash
grep -iIr "Icon=" /usr/share/applications/ | grep code
```

As for all the Ubuntu icons, that request is rather large and vague. Can you make a small list of icons you want the most?

**Comment by flipflop97** [comment]
I fixed VSCode in #31. If you still want to make a list of icon requests you can create a new issue for it.
