### ISSUE TITLE
'Home' icon in cinnamon

### ISSUE THREAD

**Issue by ayanb1991** [flipflop97/Mato#30]
in Linux Mint 18.2 'Home' icon is missing. I think the whole icon package not working properly in Linux Mint 18.2 or Cinnamon. Working perfectly in Gnome. Sidebar icons in 'Nemo' also looking bad with dark background.
![sidebar](https://user-images.githubusercontent.com/14938120/28313009-d106a7fe-6bd2-11e7-8bfb-6513450daf87.png)

**Comment by flipflop97** [comment]
I didn't add the home folder icon yet indeed, this also applies to gnome, I'll add it soon.

The icons in the sidebar look bad because it uses the full color icons (which are optimized for multiples of 24x24, not for 16x16 yet) instead of the symbolic ones. See #4.

**Comment by flipflop97** [comment]
I added the [home](https://flipflop97.github.io/Mato/#places/user-home) icon.

I can't do anything about Nemo not using the symbolic icons and I won't make separate light/dark icon packs. The scaling issue will live on in #4.

**Comment by ayanb1991** [comment]
Okey, Thanks for the 'home' icon. Will wait for 'Nemo' to support Symbolic icons in sidebar. However, Great Work.
