### ISSUE TITLE
Add some applications

### ISSUE THREAD

**Issue by MarianaPicolo** [flipflop97/Mato#31]
Could you add icons for:
 -  [x] Calibre
 -  [x] Synaptic
 -  [x] GNOME Dictionary
 -  [x] _Spotify (maybe)_

Thanks.

**Comment by MarianaPicolo** [comment]
PS: The icon of VS Code doesn't show up, so I did the following command on my terminal:
> grep -iIr "Icon=" /usr/share/applications/ | grep code 

  It results this:
> /usr/share/applications/code.desktop:Icon=code
> /usr/share/applications/code.desktop:Icon=code

**Comment by flipflop97** [comment]
Thanks, I added a symlink so the VSCode icon should now appear for you.
