### ISSUE TITLE
add openshot icon

### ISSUE THREAD

**Issue by ramzydoni** [flipflop97/Mato#32]
' Mato '  These icons are the best future icons in Linux I wish the developer success in the project

| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `openshot`| `openshot` | `openshot.desktop` | ![original](http://www.omgubuntu.co.uk/wp-content/uploads/2016/01/openshot-logo.png) |

Description: `Openshot video editor`

Website: `www.openshot.org`

thanks

**Comment by ramzydoni** [comment]
i don t understand why my request is closed ؟

**Comment by flipflop97** [comment]
For me the icon name of Openshot is `openshot-qt`. So I just added that one without thinking of aliases. If your os uses `openshot` i'll add a symlink for that one.
