### ISSUE TITLE
Only inherit themes which are really needed

### ISSUE THREAD

**Issue by alexxcons** [flipflop97/Mato#39]
Hi Mato team,

now that the [related xdg merge request](https://gitlab.freedesktop.org/xdg/default-icon-theme/-/merge_requests/5) got merged and v0.18 of the spec got released, I am starting my mission to get the "Inherits" attribute right for popular icon-themes to prevent potentially missing icons 🙂

[Currently Mato has](https://github.com/flipflop97/Mato/blob/master/src/static/index.theme#L4):

> Inherits=Adwaita,gnome,hicolor

I wonder why `gnome` and `Adwaita` are listed here ... is Mato lacking fd.org icons which need to be provided by these?

If there is no strong reason to keep them in the Inherits list, I would suggest dropping them.

If one/some of the other themes need to stay on the list for some reason, it makes sense to have a section in the README.md to explain packagers that the `mato-icon-theme` package should have a hard dependency on the other listed themes.

**Comment by flipflop97** [comment]
Hi, thank you for your interest in this project and your initiative 😄. However, I'm not maintaining this icon pack anymore.

I once made this icon theme when GNOME icons were using the 3D-ish style I didn't like. The icons shipped today are a huge improvement, and transcend the looks of Mato for me. Once I get to it, I'll achive the repo and add an announcement.
