### ISSUE TITLE
Setup OpenSUSE Build Service

### ISSUE THREAD

**Issue by ArjonBu** [flipflop97/Mato#6]
Can you please use Opensuse build service? It creates repos and binaries for all distros for free. This way we get the updates without checking every week or so. Thanks.

**Comment by flipflop97** [comment]
Sounds interesting. But from what I can see that service creates package files (which shouldn't be that hard to do manually) and allows creating repos only for openSUSE, so that wouldn't really make updating easier for other distros. 

There are open issues for native installation methods on various distros which enables automatic updating (#1 #2 #7). Also, I'll probably add an easier method for updating on all Linux distros soon, probably with a .desktop icon.

**Comment by ArjonBu** [comment]
It creates binaries and repos for all distros please read the section "For Packagers" at https://en.opensuse.org/Portal:Build_Service 

One example which was done by one theme and it uses OBS https://software.opensuse.org/download.html?project=home%3AHorst3180&package=arc-theme

**Comment by flipflop97** [comment]
Ah, that makes it much more useful. I'll look into it soon.

**Comment by ArjonBu** [comment]
Thanks! Please reply here when you do.

**Comment by flipflop97** [comment]
Ok, so I tried this multiple times now without success. The bad ui of OBS certainly isn't helping as is the little amount of documentation that isn't even complete/understandable sometimes. I got as far as automatically getting an archive made by the _service file but I can't seem to manually set its name or uncompress it, let alone use it by the build services. If someone can help me by linking an actually useful documentation/tutorial or setting the necessary files up for me I would be really thankful. But until then I'll stop working on this issue.

**Comment by flipflop97** [comment]
https://software.opensuse.org/download/package?project=home%3Aflipflop97%3Amato-icons&package=mato-icons

Should've thought earlier about looking at other OBS projects. I finally managed to get something working. It's not available for all OSes yet and it doesn't update automatically. I also haven't tested anything yet, so feel free to try and report if things are not working here.

**Comment by ArjonBu** [comment]
Seems to be working fine on Fedora 26.

**Comment by Vistaus** [comment]
If you want to push easy updates on other distros, why don't you just use Flatpak (or, alternatively, Snap)? You can set up a repo real easy.

**Comment by flipflop97** [comment]
Well, afaik flatpak and snap are both made to run sandboxed applications. They can't really touch your system while installing, so I don't think they'll be an option in this case. I'm not 100% sure if this is indeed also the case for snap packages but then again, snap is mostly connected to Ubuntu and not yet really an universal option. So i'll stick to manual and OBS installations for now.

**Comment by flipflop97** [comment]
The OBS is now officially in use and my plan for Ubuntu and Debian is to use launchpad as that integrates better with Ubuntu. I will mark this issue as done.
